### ISSUE TITLE
ENH: Separate non-unique and non-monotonic indices in test instrument kwargs

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#1094]
**Is your feature request related to a problem? Please describe.**
Currently `malformed_index` will make an index that is both non-unique and non-monotonic.  These should be separate for different testing purposes.

**Describe the solution you'd like**
- [x] Use separate functions to create non-monotonic and non-unique indices -- #1092 
- [x] Implement `non_monotonic_index` kwarg for test instruments -- #1092
- [x] Implement `non_unique_index` kwarg for test instruments -- #1096
- [x] Deprecate `malformed_index` and update usage in unit tests -- #1096
- [x] Remove `malformed_index` in a future version

**Describe alternatives you've considered**
Keep the solution in #1092 which is required for testing.  The kwargs become more confusing at this point though.

**Additional context**
Some instrument functionality requires non-monotonic but not non-unique (see #1005).
