### ISSUE TITLE
TST: Standardized instrument tests with inheritance

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#327]
**Is your feature request related to a problem? Please describe.**
As the instrument objects migrate to other packages, we need a reliable way of testing them.  

**Describe the solution you'd like**
Ideally, a uniform testing package would exist in the main pysat routine that can be imported into instrument libraries for testing.  The test routine would:
1) check for local modules
2) populate a list of instruments and data products to check
3) run through the standardized tests

Note that this change should follow or incorporate the ftp flags proposed in #156.  This could either precede or follow the expanded tests proposed in #180.  In terms of triage I think this should precede those tests.

**Additional context**
Note that as we migrate to pytest, `init` and `yield` are not allowed in tests.  This requires the current setup to be rewritten using a different construction in order to get tests to run.  Decorators, `setup` and `teardown` are allowed.

The testbed for this can be the sgp4 instrument (see pysat/pysatMissionPlanning#3).

Tasks:
- [x] Rewrite `test_instruments` to remove `init` and `yield` - fixed in #390 
- [x] Incorporate FTP flags into instruments and use to determine whether tests are run on Travis CI (#156) -- fixed in #391 
- [x] Verify inheritance of tests using pysatModels  -- completed in pysat/pysatModels#33
- [x] Provide a tutorial for new users wanting to build their own instrument libraries in documentation  -- addressed in #415

**Comment by jklenzing** [comment]
Closing with merge of #415
