### ISSUE TITLE
MAINT: hardwired travis code needs to be removed

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#777]
**Is your feature request related to a problem? Please describe.**
In the init file, a data directory is automatically set if the environment is on travis.  This is no longer run with the migration to github actions, however, it may need to remain for the time being for the penumbra packages.

**Describe the solution you'd like**
Once all packages have been updated, this line can be removed.

**Describe alternatives you've considered**
:duck:

**Additional context**
Packages that have migrated to github actions or are otherwise not affected.  Checked after merge into develop or if CI not used yet.
- [x] pysatKamodo -- no CI yet
- [x] pysatMissions -- pysat/pysatMissions#47
- [x] pysatModels -- pysat/pysatModels#72
- [x] pysatSeasons -- pysat/pysatSeasons#23
- [x] pysatAMISR -- no CI yet
- [x] pysatCDAAC -- pysat/pysatCDAAC#20
- [ ] pysatMadrigal -- pysat/pysatMadrigal#45
- [x] pysatNASA -- pysat/pysatNASA#56
- [x] pysatSpaceWeather -- pysat/pysatSpaceWeather#44
- [x] pysatIncubator -- pysat/pysatIncubator#14

**Comment by jklenzing** [comment]
When migrated, make sure to update the status chart here: https://github.com/pysat/pysat/wiki/Pysat-Ecosystem-Status-Chart

**Comment by jklenzing** [comment]
Clearing the milestone since we may need travis support on pysatMadrigal for a while.

**Comment by jklenzing** [comment]
Noting that the current travis.yml in pysatMadrigal does manually set the data directory, so this could be be considered compliant.

**Comment by jklenzing** [comment]
Closing with merge of #806.  pysatMadrigal changes documented there.
