### ISSUE TITLE
TST/DOC: automate docstring linting

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#860]
**Is your feature request related to a problem? Please describe.**
Our docstring standards vary wildly.

**Describe the solution you'd like**
`flake8-docstrings` will add style checks to the docstrings throughout.  Adding this the list of test_requirements will automate this in the tests on GA (runs along with flake8).  Includes:
- Check for imperative tense in one line description
- Check for periods at end of one-line description
- Check for whitespace and blank lines
- Check for top level public module docstrings

Once files are brought up to code, the following changes should be implemented:
- [x] Add `flake8-docstrings` and `hacking` to test_requirements.txt -- #884
- [x] Update flake8 command in main.yml to include `--select=D,E,F,H,W` -- #884

**Describe alternatives you've considered**
Pain and suffering during the review process

**Additional context**
#565 needs to implemented first.  The docstrings throughout also need to cleaned up for style.

Current violations
- [x] ./setup.py -- #868
- [x] ./pysat/_meta.py -- #884
- [x] ./pysat/__init__.py -- #868
- [x] ./pysat/_files.py -- #884
- [x] ./pysat/_orbits.py -- #884
- [x] ./pysat/_instrument.py -- #884
- [x] ./pysat/_params.py -- #869
- [x] ./pysat/_constellation.py -- #879
- [x] ./pysat/constellations/__init__.py -- #879
- [x] ./pysat/constellations/testing_empty.py -- #879
- [x] ./pysat/constellations/single_test.py -- #879
- [x] ./pysat/constellations/testing.py -- #879
- [x] ./pysat/tests/__init__.py  -- #868
- [x] ./pysat/tests/ci_test_class.py -- #868
- [x] ./pysat/tests/instrument_test_class.py -- #867
- [x] ./pysat/tests/test_instruments.py -- #866
- [x] ./pysat/tests/test_meta.py -- #864
- [x] ./pysat/tests/test_methods_general.py -- #877
- [x] ./pysat/tests/test_orbits.py -- #781 
- [x] ./pysat/tests/registration_test_class.py -- #869
- [x] ./pysat/tests/test_constellation.py -- #879
- [x] ./pysat/tests/test_custom.py -- #877
- [x] ./pysat/tests/test_files.py -- #868
- [x] ./pysat/tests/test_instrument.py -- #880, #881
- [x] ./pysat/tests/test_params.py -- #869
- [x] ./pysat/tests/test_registry.py -- #869
- [x] ./pysat/tests/test_utils.py -- #858
- [x] ./pysat/tests/test_utils_coords.py -- #867
- [x] ./pysat/tests/test_utils_files.py -- #867
- [x] ./pysat/tests/test_utils_testing.py -- #867
- [x] ./pysat/tests/test_utils_time.py -- #867
- [x] ./pysat/utils/files.py -- #867
- [x] ./pysat/utils/time.py -- #867
- [x] ./pysat/utils/coords.py -- #867
- [x] ./pysat/utils/registry.py -- #867
- [x] ./pysat/utils/__init__.py -- #867
- [x] ./pysat/utils/_core.py -- #867
- [x] ./pysat/utils/testing.py -- #867
- [x] ./pysat/instruments/__init__.py --#866
- [x] ./pysat/instruments/pysat_testing_xarray.py -- #866
- [x] ./pysat/instruments/pysat_testing2d.py -- #866
- [x] ./pysat/instruments/pysat_testing2d_xarray.py -- #866
- [x] ./pysat/instruments/pysat_testmodel.py - #866
- [x] ./pysat/instruments/pysat_testing.py -- #866
- [x] ./pysat/instruments/methods/__init__.py -- #866 
- [x] ./pysat/instruments/methods/testing.py -- #866 
- [x] ./pysat/instruments/methods/general.py -- #866
- [x] ./pysat/instruments/templates/__init__.py -- #866
- [x] ./pysat/instruments/templates/template_instrument.py -- #866
- [x] ./docs/conf.py -- #868

**Comment by jklenzing** [comment]
Errors we get throughout the code:
```
12    D100 Missing docstring in public module
57    D101 Missing docstring in public class
142   D102 Missing docstring in public method
1     D104 Missing docstring in public package
2     D105 Missing docstring in magic method
6     D107 Missing docstring in __init__
174   D200 One-line docstring should fit on one line with quotes
222   D202 No blank lines allowed after function docstring
11    D204 1 blank line required after class docstring
27    D205 1 blank line required between summary line and description
5     D209 Multi-line docstring closing quotes should be on a separate line
147   D210 No whitespaces allowed surrounding docstring text
501   D400 First line should end with a period
202   D401 First line should be in imperative mood
4     D403 First word of the first line should be properly capitalized
```

The first number is the number of instances.  The error flags starting with D are the violation references.  We can turn these off in the metadata for the project if we don't want a specific rule.

**Comment by jklenzing** [comment]
Proposal after discussion with @aburrell: ignore D200 and D202

**Comment by jklenzing** [comment]
These have been updated in the `flake8/docstrings` series of branches, with the final one numbered 10.  Given the large number of changes (>1000 additions), these will be pushed as a series of reviewable sized branches.

**Comment by jklenzing** [comment]
This goes beyond docstrings, but the `hacking` package includes more community-defined standards.  We could pull this in as well, turning off checks we don't want.  The additional problems this finds are:
```
2     H101: Use TODO(NAME)
51    H238: old style class declaration, use new style (inherit from `object`)
5     H301: one import per line
14    H306: imports not in alphabetical order (pysat.utils, pysat._instrument.instrument)
35    H404: multi line docstring should start without a leading new line
119   H405: multi line docstring summary not separated with an empty line
```
@aburrell, H405 is the error you're looking for, but this does mean that the following is not allowed:
```
"""really long one-line docstring.
"""
```
The following would be allowed
```
"""somewhat shorter docstring."""
```
```
"""Really long docstring.

"""
```

**Comment by aburrell** [comment]
That will result in less changes to all of our docstrings, so I am ok with it.

**Comment by jklenzing** [comment]
I'll go ahead and update the current pull.  I don't see any of these we should ignore yet, but let me know if something looks weird.  If we format our TODO comments as TODO(#ISSUE), it passes and conforms to our style guide.

**Comment by jklenzing** [comment]
@aburrell, any thoughts on "one import per line"?  This will mainly affect the init files, eg
```
from pysat.utils import coords, files, time, registry, testing
from pysat.utils._core import scale_units, listify, load_netcdf4
from pysat.utils._core import NetworkLock, generate_instrument_list
from pysat.utils._core import available_instruments
from pysat.utils._core import display_available_instruments
```

**Comment by aburrell** [comment]
I like it when I'm debugging, makes for useful error messages.

From: Jeff Klenzing ***@***.***>
Reply-To: pysat/pysat ***@***.***>
Date: Tuesday, August 10, 2021 at 16:31
To: pysat/pysat ***@***.***>
Cc: "Burrell, Angeline" ***@***.***>, Mention ***@***.***>
Subject: Re: [pysat/pysat] TST/DOC: automate docstring linting (#860)


@aburrell<https://github.com/aburrell>, any thoughts on "one import per line"? This will mainly affect the init files, eg

from pysat.utils import coords, files, time, registry, testing

from pysat.utils._core import scale_units, listify, load_netcdf4

from pysat.utils._core import NetworkLock, generate_instrument_list

from pysat.utils._core import available_instruments

from pysat.utils._core import display_available_instruments

**Comment by jklenzing** [comment]
Looking downstream, after #879, we have
flake8/docstrings6 -- test_instrument part 1 of 3
flake8/docstrings7 -- test_instrument part 2 of 3
flake8/docstrings8 -- test_instrument part 3 of 3
flake8/docstrings9 -- _instrument
flake8/docstrings10 -- remainder of code and adding tests to main.yml

If some of these are larger than expected, they might get broken up further.

**Comment by jklenzing** [comment]
Closing with merge of #884
