### ISSUE TITLE
STY: group test classes under a single directory

### ISSUE THREAD

**Issue by jklenzing** [pysat/pysat#904]
**Is your feature request related to a problem? Please describe.**
In #903, we've begun moving common tests to a "classes" directory stored under the test directory.  These tests are not run directly by pytest, but inherited through other test classes starting with the "Test" prefix.

**Describe the solution you'd like**
This should be made consistent for the other test classes.  Deprecation warnings need to be added for classes used by downstream packages.  Naming convention should be made consistent with previous work.
- [x] ci_test_class.py -- #916
- [x] instrument_test_class.py -- #915
- [x] registration_test_class.py -- #916
- [x] Remove deprecated classes in 3.2

**Describe alternatives you've considered**
Inconsistency

**Additional context**
See #870

**Comment by jklenzing** [comment]
@aburrell, @rstoneback, for the ci_test_class and registration_test_class, should we just move these or deprecate them, similar to #915?  Not sure if these are used outside the core code.

**Comment by aburrell** [comment]
I don't know :(. If they aren't, I say we just move them.

From: Jeff Klenzing ***@***.***>
Reply-To: pysat/pysat ***@***.***>
Date: Friday, October 1, 2021 at 15:50
To: pysat/pysat ***@***.***>
Cc: "Burrell, Angeline" ***@***.***>, Mention ***@***.***>
Subject: Re: [pysat/pysat] STY: group test classes under a single directory (#904)


@aburrell<https://github.com/aburrell>, @rstoneback<https://github.com/rstoneback>, for the ci_test_class and registration_test_class, should we just move these or deprecate them, similar to #915<https://github.com/pysat/pysat/pull/915>? Not sure if these are used outside the core code.

**Comment by jklenzing** [comment]
Tested against the other packages.  Safe to just move these classes.

**Comment by jklenzing** [comment]
Bumping milestone.  Removal of deprecated items in 3.2.0 needed.

**Comment by jklenzing** [comment]
branch downstream of #1143

**Comment by jklenzing** [comment]
branch downstream of #908
